czapla/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^', include('home.urls', namespace='home')),
                       url(r'^profile/', include('profile.urls', namespace='profile')),
                       url(r'^group/', include('group.urls', namespace='group')),
                       url(r'^item/', include('item.urls', namespace='item')),
                       url(r'^order/', include('order.urls', namespace='order')),
                       url(r'^meal/', include('meal.urls', namespace='meal')),
                       url(r'^admin/', include(admin.site.urls)),)

group/urls.py
from django.conf.urls import patterns, include, url
from group import views

urlpatterns = patterns('',
                       url(r'^(?P<group_id>[0-9]+)',views.details, name='details'))

home/urls.py
from django.conf.urls import patterns, include, url
from home import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'))

meal/urls.py
from django.conf.urls import patterns, include, url
from meal import views

urlpatterns = patterns('',
                       url(r'^restaurant/group/(?P<group_id>[0-9]+)',views.restaurant, name='restaurant'),
                       url(r'^select/(?P<order_id>[0-9]+)',views.select, name='select'))

group/models.py
from django.db import models

group/views.py
#-*- coding: utf-8 -*-
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import Group
from django.db.models import Q
from order.models import Order


def details(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    orders = Order.objects.filter(Q(group=group_id), Q(order_time__gt=datetime.datetime.now())).order_by('order_time')
    if not request.user.is_authenticated():
        messages.warning(request, 'Musisz być zalogowany, żeby zobaczyć grupy')
        return redirect('profile:index')
    else:
        if not request.user.groups.filter(id=group_id).exists():
            messages.warning(request, 'Nie należysz do tej grupy')
            return redirect('profile:index')
        else:
            return render(request, 'group/details.html', {'group':group, 'orders':orders.all(), 'now':datetime.datetime.now()})

group/templates/group/details.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="page-header">
        <h1>{{group.name}}</h1>
    </div>

    {% if orders.count > 0 %}
        <h3>Zamówienia grupy {{group.name}}</h3>
        <div class="list-group">
        {% for order in orders %}
            <a href="{% url 'order:details' order.id %}" class="list-group-item">
                {% if order.order_time|date:"d-m-Y" == now|date:"d-m-Y" %}
                    <span class="label label-success">Dzisiaj {{order.order_time|date:"H:i"}}</span>
                {% else %}
                    <span class="label label-info">{{order.order_time|date:"d-m-Y H:i"}}</span>
                {% endif %}
                {{order.name}}</a>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">Nie ma jeszcze żadnych zamówień</div>
    {% endif %}
    <p>
        <a href="{% url 'meal:restaurant' group.id %}" class="btn btn-primary" >Nowe zamówienie</a>
    </p>
    <p>
        <a href="{% url 'profile:index' %}" class="btn btn-info" >Wstecz</a>
    </p>


{% endblock %}

group/templates/group/index.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="page-header">
        <h1>Welcome {{user.username}}</h1>
    </div>
    {% if user.groups.all.count > 0 %}
        <h3>Your groups</h3>
        <div class="list-group">
        {% for group in user.groups.all %}
            <a href="{% url 'group:details' group.id %}" class="list-group-item">{{group.name}}</a>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">Nie należysz jeszcze do żadnej grupy</div>
    {% endif %}
{% endblock %}