czapla/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^', include('home.urls', namespace='home')),
                       url(r'^profile/', include('profile.urls', namespace='profile')),
                       url(r'^group/', include('group.urls', namespace='group')),
                       url(r'^item/', include('item.urls', namespace='item')),
                       url(r'^order/', include('order.urls', namespace='order')),
                       url(r'^meal/', include('meal.urls', namespace='meal')),
                       url(r'^admin/', include(admin.site.urls)),)

group/urls.py
from django.conf.urls import patterns, include, url
from group import views

urlpatterns = patterns('',
                       url(r'^(?P<group_id>[0-9]+)',views.details, name='details'))

home/urls.py
from django.conf.urls import patterns, include, url
from home import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'))

profile/urls.py
from django.conf.urls import patterns, include, url
from profile import views

urlpatterns = patterns('',
                       url(r'^$',views.index, name='index'),
                       url(r'^register',views.register, name='register'),
                       )

profile/models.py
from django.db import models

# Create your models here.

profile/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.utils.datastructures import MultiValueDictKeyError

from home.forms import LoginForm, RegisterForm


def index(request):
    form = LoginForm()
    if request.POST:
        try:
            log_out = request.POST['logout']
        except MultiValueDictKeyError:
            log_out = False
        if log_out:
            logout(request)
            messages.success(request, 'Wylogowano')
            return redirect('home:index')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, 'Witaj '+username)
                return redirect('home:index')
            else:
                messages.warning(request, 'Twoje konto nie jest aktywne')
        else:
            messages.warning(request, 'Błędna nazwa użytkownika lub hasło')
    return render(request, 'profile/index.html', {'form': form})


def register(request):
    form = RegisterForm(request.POST)
    if request.POST:
        if form.is_valid():
            form.save()
            new_user = authenticate(username=request.POST['username'],
                                    password=request.POST['password1'])
            login(request, new_user)
            messages.success(request, u'Witaj %s, dziękujemy za utworzenie konta.' % (request.POST['username']))
            return redirect('home:index')
        else:
            for err in form.errors:
                messages.warning(request, form.errors[err])
    return render(request, 'profile/register.html', {'form': form})

profile/templates/profile/index.html
{% extends 'home/base.html' %}

{% block title %}
    {% if user.is_authenticated %}
       Witaj {{user.username}}.
    {% else %}
        Witaj. Zaloguj się, aby złożyć zamówienie
    {% endif %}
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="page-header">
          <h1>Witaj {{user.username}}</h1>
        </div>

        {% if user.groups.all.count > 0 %}
            <h3>Twoje grupy</h3>
            <div class="list-group">
            {% for group in user.groups.all %}
                <a href="{% url 'group:details' group.id %}" class="list-group-item">{{group.name}}</a>
            {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">Nie należysz jeszcze do żadnej grupy</div>
        {% endif %}

    {% else %}
        <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Nazwa użytkownika</label>
            {{form.username}}
        </div>
        <div class="form-group">
            <label for="password">Hasło</label>
            {{form.password}}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Zaloguj się <i class="fa fa-sign-in"></i></button>
        </div>
        </form>

        <div class="panel panel-default">
          <div class="panel-body">
            Nie masz jeszcze konta? <a href="{% url 'profile:register' %}">Zarejestruj się!</a>
          </div>
        </div>
    {% endif %}
{% endblock %}