czapla/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^', include('home.urls', namespace='home')),
                       url(r'^profile/', include('profile.urls', namespace='profile')),
                       url(r'^group/', include('group.urls', namespace='group')),
                       url(r'^item/', include('item.urls', namespace='item')),
                       url(r'^order/', include('order.urls', namespace='order')),
                       url(r'^meal/', include('meal.urls', namespace='meal')),
                       url(r'^admin/', include(admin.site.urls)),)

home/urls.py
from django.conf.urls import patterns, include, url
from home import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'))

meal/urls.py
from django.conf.urls import patterns, include, url
from meal import views

urlpatterns = patterns('',
                       url(r'^restaurant/group/(?P<group_id>[0-9]+)',views.restaurant, name='restaurant'),
                       url(r'^select/(?P<order_id>[0-9]+)',views.select, name='select'))

order/urls.py
from django.conf.urls import patterns, include, url
from order import views

urlpatterns = patterns('',
                       url(r'^add',views.add, name='add'),
                       url(r'^(?P<order_id>[0-9]+)',views.details, name='details'))

order/models.py
from django.db import models
from django.contrib.auth.models import Group, User

from meal.models import Restaurant


class Order(models.Model):
    name = models.CharField(max_length=200)
    group = models.ForeignKey(Group)
    user = models.ForeignKey(User)
    restaurant = models.ForeignKey(Restaurant)
    order_time = models.DateTimeField()

    def __unicode__(self):
        return self.name

order/views.py
#-*- coding: utf-8 -*-
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import Group

from order.models import Order
from item.models import Item
from meal.models import Restaurant


def details(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    items = Item.objects.filter(order=order_id)
    if not request.user.is_authenticated():
        messages.warning(request, 'Musisz być zalogowany, żeby zobaczyć zamówienia')
        return redirect('profile:index')
    else:
        if not request.user.groups.filter(id=order.group.id).exists():
            messages.warning(request, 'To zamówienie nie należy do Twojej grupy')
            return redirect('profile:index')
        else:
            return render(request, 'order/details.html', {'order': order, 'items': items.all()})


def add(request):
    model = Order()
    if request.POST:
        group = get_object_or_404(Group, pk=request.POST.get('group'))
        restaurant = get_object_or_404(Restaurant, pk=request.POST.get('restaurant'))
        time = request.POST.get('hours')+':'+request.POST.get('minutes')
        order_date = datetime.datetime.strptime(request.POST.get('date')+' '+time, '%d-%m-%Y %H:%M')
        model.name = request.POST.get('name')
        model.user = request.user
        model.group = group
        model.restaurant = restaurant
        model.order_time = order_date
        model.save()
        messages.success(request, 'Order created')
        return redirect('order:details', model.id)

order/templates/order/details.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="page-header">
        <h1>{{order.name}}</h1>
        <h4>Czas zamówienia: {{order.order_time}}</h4>
    </div>
    {% if items.count > 0 %}
        <h3>Lista zamawiających</h3>
        <div class="list-group">
        {% for item in items %}
            <p class="list-group-item">{{item.meal.name}} zamówione przez <a>{{item.user}}</a> <span>{{item.meal.price}}zł</span></p>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">Nie ma jeszcze żadnych zamówień dla tej listy</div>
    {% endif %}
    <p>
        <a href="{% url 'meal:select' order.id %}" class="btn btn-primary">Dopisz się</i></a>
    </p>

    <p>
        <a href="{% url 'group:details' order.group.id %}" class="btn btn-info" >Wstecz</a>
    </p>
{% endblock %}

order/templates/order/index.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="page-header">
        <h1>Welcome {{user.username}}</h1>
    </div>
    {% if user.groups.all.count > 0 %}
        <h3>Your groups</h3>
        <div class="list-group">
        {% for group in user.groups.all %}
            <a href="{% url 'group:details' group.id %}" class="list-group-item">{{group.name}}</a>
        {% endfor %}
        </div>
    {% else %}
      <div class="alert alert-warning" role="alert">Nie należysz jeszcze do żadnej grupy</div>
    {% endif %}
{% endblock %}