czapla/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^', include('home.urls', namespace='home')),
                       url(r'^profile/', include('profile.urls', namespace='profile')),
                       url(r'^group/', include('group.urls', namespace='group')),
                       url(r'^item/', include('item.urls', namespace='item')),
                       url(r'^order/', include('order.urls', namespace='order')),
                       url(r'^meal/', include('meal.urls', namespace='meal')),
                       url(r'^admin/', include(admin.site.urls)),)

group/urls.py
from django.conf.urls import patterns, include, url
from group import views

urlpatterns = patterns('',
                       url(r'^(?P<group_id>[0-9]+)',views.details, name='details'))

home/urls.py
from django.conf.urls import patterns, include, url
from home import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'))

item/urls.py
from django.conf.urls import patterns, include, url
from item import views

urlpatterns = patterns('',
                       #url(r'^$',views.index, name='index'),
                       url(r'^add/(?P<order_id>[0-9]+)/meal/(?P<meal_id>[0-9]+)',views.add, name='add'))

meal/urls.py
from django.conf.urls import patterns, include, url
from meal import views

urlpatterns = patterns('',
                       url(r'^restaurant/group/(?P<group_id>[0-9]+)',views.restaurant, name='restaurant'),
                       url(r'^select/(?P<order_id>[0-9]+)',views.select, name='select'))

meal/models.py
from django.db import models
from django.contrib.auth.models import User


class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)

    def __unicode__(self):
        return self.name


class Meal(models.Model):
    name = models.CharField(max_length=200)
    restaurant = models.ForeignKey(Restaurant)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.CharField(max_length=1000)

    def __unicode__(self):
        return self.name


class Rating(models.Model):
    meal = models.ForeignKey(Meal)
    restaurant = models.ForeignKey(Restaurant)
    user = models.ForeignKey(User)
    value = models.IntegerField()
    comment = models.CharField(max_length=500)

    def stars(self):
        return range(0,self.value)

meal/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.template import Context

from order.models import Order
from meal.models import Meal, Restaurant


def restaurant(request, group_id):
    if not request.user.is_authenticated():
        messages.warning(request, 'Musisz być zalogowany, żeby utworzyć zamówienie')
        return redirect('profile:index')
    else:
        if not request.user.groups.filter(id=group_id):
            messages.warning(request, 'Nie należysz do tej grupy')
            return redirect('profile:index')
        else:
            restaurants = Restaurant.objects.all()
            hours = range(1, 24)
            return render(request, 'meal/restaurant.html', {'restaurants': restaurants.all(),
                                                            'group_id': group_id,
                                                            'hours': hours,
                                                            })


def select(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    meals = Meal.objects.filter(restaurant=order.restaurant.id)
    if not request.user.groups.filter(id=order.group.id):
        messages.warning(request, 'To zamówienie nie należy do Twojej grupy')
        return redirect('profile:index')
    else:
        return render(request,'meal/select.html',{'meals': meals.all(),'order': order})

meal/templates/meal/restaurant.html
{% extends 'home/base.html' %}

{% block content %}
    {% if restaurants.count > 0 %}
    <form method="POST" action="{% url 'order:add' %}">
        {% csrf_token %}
        <input type="hidden" value="{{group_id}}" name="group"/>
        <h3>Nazwa zamówienia</h3>
        <p class="list-group-item">
            <input type="text" name="name" placeholder="Nazwa zamówienia" required=""/>
        </p>
        <h3>Wybierz czas zamówienia</h3>
        <p class="list-group-item restaurant">
            <label for="date">Data</label><input placeholder="Data zamówienia" type="text" id="date" class="datepicker" name="date" required=""/> <i class="fa fa-calendar"></i><br/>
            <label>Godzina</label>
                <select name="hours" required="">
                    <option value=''>--</option>
                    <option value='00'>00</option>
                    {% for h in hours %}
                        <option value={{h}}> {{h}}</option>
                    {% endfor %}
                </select>

                <select name="minutes" required="">
                    <option value=''>--</option>
                    <option value='00'>00</option>
                    <option value='15'>15</option>
                    <option value='30'>30</option>
                    <option value='45'>45</option>
                </select>
        </p>
        <h3>Wybierz restaurację</h3>
        <div class="list-group">
        {% for restaurant in restaurants %}
            <p class="list-group-item restaurant"><input type="radio" value="{{restaurant.id}}" id="{{restaurant.id}}" name="restaurant" required=""/><label for="{{restaurant.id}}">{{restaurant}}</label></p>
        {% endfor %}
        </div>
        <p>
            <input type="submit" class="btn btn-primary" value="Utwórz zamówienie" />
        </p>
    {% else %}
        <div class="alert alert-warning" role="alert">Nie ma jeszcze żadnych restauracji</div>
    </form>
    {% endif %}
        <script>
            $(document).ready(function(){
                $('.restaurant').on('click',function(){
                    $(this).find('input').attr('selected');
                    $('.order-time').hide();
                    $(this).next().show();
                });

                $( '.fa-calendar').on('click',function(){
                    $('.datepicker').datepicker({
                        showOn: 'focus',
                        showButtonPanel: true,
                        dateFormat: 'dd-mm-yy',
                        minDate: 0,
                    });
                    $('.datepicker' ).focus();
                });

                 $.datepicker._gotoToday = function(id) {
                    var target = $(id);
                    var inst = this._getInst(target[0]);
                    if (this._get(inst, 'gotoCurrent') && inst.currentDay) {
                            inst.selectedDay = inst.currentDay;
                            inst.drawMonth = inst.selectedMonth = inst.currentMonth;
                            inst.drawYear = inst.selectedYear = inst.currentYear;
                    }
                    else {
                            var date = new Date();
                            inst.selectedDay = date.getDate();
                            inst.drawMonth = inst.selectedMonth = date.getMonth();
                            inst.drawYear = inst.selectedYear = date.getFullYear();
                            // the below two lines are new
                            this._setDateDatepicker(target, date);
                            this._selectDate(id, this._getDateDatepicker(target));
                    }
                    this._notifyChange(inst);
                    this._adjustDate(target);
                }
            });
        </script>

{% endblock %}

meal/templates/meal/select.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="page-header">
        <h1>{{order.restaurant}}</h1>
        <h3>{{order.name}}</h3>
        <h4>{{order.order_time}}</h4>
    </div>

    {% if meals.count > 0 %}
        <h3>Dania restauracji {{order.restaurant}}</h3>
        <div class="list-group">
        {% for meal in meals %}
            <a href="{% url 'item:add' order_id=order.id meal_id=meal.id %}" class="list-group-item">{{meal}}</a>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">Nie ma jeszcze żadnych dań w tej restauracji</div>
    {% endif %}
    <p>
        <a href="{% url 'order:details' order.id %}" class="btn btn-info" >Wstecz</a>
    </p>
{% endblock %}